name: Aspire Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  aspire-integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build solution
      run: dotnet build --configuration Release --no-restore
    
    - name: Run Aspire integration tests
      run: |
        dotnet test CodeUI.AspireTests \
          --configuration Release \
          --no-build \
          --verbosity normal \
          --collect:"XPlat Code Coverage" \
          --results-directory ./aspire-coverage \
          --logger trx \
          --logger "console;verbosity=detailed"
    
    - name: Run unit tests
      run: |
        dotnet test CodeUI.Tests \
          --configuration Release \
          --no-build \
          --verbosity normal \
          --collect:"XPlat Code Coverage" \
          --results-directory ./unit-coverage \
          --logger trx \
          --logger "console;verbosity=detailed"
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: aspire-test-results
        path: |
          ./aspire-coverage/
          ./unit-coverage/
        retention-days: 30
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      if: always()
      with:
        directory: ./aspire-coverage,./unit-coverage
        flags: integration-tests
        name: codecov-aspire